---
title: "Importance of Intent and Outcome of a Situation in the Perception of Happiness"
author: Ellen Schmidt, Department of Cognitive Science, University of Osnabrück
output: html_document
references:
- id: phillips
  title: The Good in Happiness
  author:
  - family: Phillips et.al.
    given: Jonathan
  volume: 1
  URL: https://philarchive.org/archive/PHITGIv2
  publisher: Oxford University Press
  page: 275
  type: article-journal
  issued:
    year: 2014
---


This is a conceptual replication of experiment 6 of J. Phillips et.al. in the Oxford Studues in Experimental Philosophy Vol. 1, Chapter 10 "The Good in Happiness".

Since it became clear in earlier studies that the normative evaluations influenced the ordinary judgment of happiness [cf.@phillips]. This 6th experiment was designed to find out where exactly the normative judgment applied: on the agents *actual* life or on the life he or she *believed* to be living. 

A story about a character named Sarah was created. She worked in a childrens hospital and it was clearly stated, that she was very happy about that, specifically making sure that the participants understood her to have "high levels of positive affect, low levels of negative affect and high life-satisfaction"[@phillips]. In half the stories she thought herself to be harming children, in the other half helping them. And eventually her actions turned out to be good or bad 10 years later, thus creating four vignettes for  Sarahs life. 




The reasons this experiment wasn't replicated exactly, were

1. the fact that when Sarah was intenting to hurt the children, but eventually happened to help them, the rating of her actual life value was surprisingly low, even lower than when her bad intention and outcome aligned. 

    The reason for that was believed to be in the usage of the word *pesticide* in this context. Since the is already a negative connotation of this term in connection with ingestions, it might have been harder for participants to believe that it helped the children on some level.

2. the effect of Sarahs actions weren't huge. Only *some of the children* got better or more sick. 

To attend to both flaws the stories for this replication were made more abstract to avoid any inclinations people have about certain terms or personal afflictions and more drastic, so as to make it a bit clearer that the characters life value actually changed with their action and the result.

## Design

Participants will see a story about a fictitious character. They are asked to think about how happy the character is and adjust a slider, ranging from "not happy" to "very happy", accordingly. Only when the slider-button has been moved, a next-button will appear and allow the participant to continue. 

## Participants

**Recruitment:** Subjects will be recruited via mailing lists at the University of Osnabrück, as well as social media (Facebook) of the author. Participants will not be paid. 

**Inclusion/Exclusion:** Anyone without sufficient understanding of the English language cannot take part in the study.  *(technische constraints?)*  

## Materials

The characters and stories are all fictitious and introduced as aliens. There are two main components to each story, good or evil intent, and good or bad outcome, making up four conditionsets of (intent/outcome). 
Each story consists of three parts. For one character the first part will always be the same, describing the initial situation. The second part will be randomly assigned to either good or evil intent. The third part will contain the outcome, which is unique though to the intent chosen beforehand, i.e. the third part is different for good outcome/good intent and good outcome/evil intent. So the story-combinations for one character branch out like a tree instead of a network.

## Procedure

The task is very shortly explained on the *introductory screens*.

As there are four different conditionsets and also four different characters, participants will have four trials, each with a random combination of a character and a conditionset.
Participants must read through the story and then decide, how happy or not happy the character is. They adjust a slider and only then get the option to continue. 

There will be no practice trials as it is assumed that adjusting a slider is straightforward and easily manageable. 

At the end participants see a *post test screen*, where they can leave additional information about their person. This is optional. 


## Data preparation & exploration

## Analysis

model1 <- lm(rating_slider ~ intent + outcome, mydata)

summary(model1)

layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page
plot(model1)
## Results

## Discussion

## References
